### ISSUE TITLE
Alternative to active-win?

### ISSUE THREAD

**Issue by sulaysumaria** [paymoapp/node-active-window#8]
Why shouldn't I use https://www.npmjs.com/package/active-win?

**Comment by gergof** [comment]
You could use that package. It even has some advantages over this one.

Both libraries can:
- get the window title
- get the application name
- get the application's path
- get the application's PID

What [active-win](https://www.npmjs.com/package/active-win) can do and [@paymoapp/active-window](https://www.npmjs.com/package/@paymoapp/active-window) can not:
- get the window bounds (x, y, height, width)
- on MacOS get the URL loaded in browsers
- get the list of all open windows
- uses standalone executables/system commands that are called with child_process
- can get the window's memory usage

What [@paymoapp/active-window](https://www.npmjs.com/package/@paymoapp/active-window) can do and [active-win](https://www.npmjs.com/package/active-win) can not:
- uses native (C++, ObjectiveC++) addons to interact with system APIs so there're no child_process calls, the code can be signed and operating systems won't complain about the signature (Gatekeeper usually complains about electron applications including unsigned third party executables)
- can fetch the application's icon as a high resolution PNG
- on windows can determine if the application is an UWP application and return the UWP package ID if so
- can operate in subscription mode (you don't have to poll for the active window, you will be notified as soon as the window changes)
- lower memory footprint and resource usage and faster response times given that you don't have to spin up a new process on every request
- has partial support for Wayland on linux
