### ISSUE TITLE
when import the package

### ISSUE THREAD

**Issue by basetnt** [paymoapp/node-active-window#9]
[vite:node-asset] Could not load /myapp/node_modules/@paymoapp/active-window/build/Release/PaymoActiveWindow.node?commonjs-proxy (imported by node_modules/@paymoapp/active-window/dist/index.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00/myapp/node_modules/@paymoapp/active-window/build/Release/PaymoActiveWindow.nod..
<img width="877" alt="image" src="https://github.com/paymoapp/node-active-window/assets/60865911/cfdda5e2-cba0-416e-9a01-fa1bfdd9bd20">

**Comment by gergof** [comment]
First of all, this is a NodeJS only library, it will not work without NodeJS (in a browser env for example). If you're using vite for bundling an electron application for example, then you have to import this library in your main process and use IPC to communicate with the renderer. As for the bundler settings, you have to tell Vite that this library is an external module so it won't try to bundle binary files (the .node files). This can be done using the `build.rollupOptions.external` setting.

For example:
```js
import { builtinModules } from 'module';

import { defineConfig } from 'vite';

export default defineConfig({
	root: __dirname,
	envDir: process.cwd(),
	build: {
		outDir: '../../dist_electron/electron/main',
		emptyOutDir: true,
		sourcemap: true,
		target: 'node16',
		lib: {
			entry: 'index.ts',
			formats: ['cjs']
		},
		rollupOptions: {
			external: [
				'@paymoapp/active-window', // HERE you define that you won't like this lib to get bundled
				...builtinModules.flatMap(p => [p, `node:${p}`])
			],
			output: {
				entryFileNames: '[name].cjs',
				interop: 'auto'
			}
		}
	}
});
```
